services:
  - type: web
    name: karaoke-bot
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_VERSION
        value: 20.11.1
      - key: DISCORD_BOT_TOKEN
        sync: false
      - key: ROBLOX_API_KEY
        sync: false
      - key: ROBLOX_USER_ID
        sync: false
      - key: MUSIC_API_URL
        sync: false
